import type { Metadata } from 'next';
import Link from 'next/link';
import JsonLd from '@/components/JsonLd';
import { absoluteUrl, breadcrumbSchema, buildMetadata, SITE } from '@/lib/seo';

const title = 'Safer grocery shopping and storage';
const description = 'Inspect packaging and dates, keep raw food separate, maintain safe temperatures, cook thoroughly and use safe water when handling groceries.';
export const metadata: Metadata = buildMetadata({ title, description, path: '/guides/safer-grocery-storage' });

export default function SaferGroceryStoragePage() {
  const url = absoluteUrl('/guides/safer-grocery-storage');
  const article = { '@context': 'https://schema.org', '@type': 'Article', headline: title, description, url, datePublished: '2026-08-20', dateModified: '2026-08-20', inLanguage: SITE.language, author: { '@type': 'Organization', name: 'NOVA MART Retail Operations Team', url: absoluteUrl('/about') }, publisher: { '@id': `${SITE.url}/#organization` }, mainEntityOfPage: url };
  const crumbs = breadcrumbSchema([{ name: 'Home', path: '/' }, { name: 'Guides', path: '/guides' }, { name: title, path: '/guides/safer-grocery-storage' }]);
  return <article className="shell page max-w-4xl"><JsonLd data={[article, crumbs]} /><nav className="breadcrumbs" aria-label="Breadcrumb"><Link href="/">Home</Link><span>›</span><Link href="/guides">Guides</Link><span>›</span><span aria-current="page">Food safety</span></nav><header className="mb-10"><p className="eyebrow">FOOD SAFETY GUIDE</p><h1 className="text-4xl font-bold tracking-tight">{title}</h1><p className="mt-5 text-xl leading-8 text-slate-700">The safest routine is simple: inspect packaging and dates, separate raw from ready-to-eat food, refrigerate perishables promptly, cook thoroughly, and use safe water. These steps follow the World Health Organization’s five keys to safer food.</p><p className="mt-4 text-sm text-slate-500">Published 20 August 2026 · Reviewed by the NOVA MART Retail Operations Team · 6 minute read</p></header><div className="space-y-9 text-base leading-7 text-slate-700">
    <section><h2 className="text-2xl font-bold text-slate-950">Why these checks matter</h2><p className="mt-3">WHO estimated that 866 million people became ill after eating contaminated food in 2021 and that unsafe food can cause more than 200 diseases. Food safety therefore matters from the shelf to preparation at home. <a className="font-semibold text-emerald-700 underline" href="https://www.who.int/news-room/fact-sheets/detail/food-safety" target="_blank" rel="noreferrer">WHO food-safety fact sheet</a></p></section>
    <section><h2 className="text-2xl font-bold text-slate-950">1. Inspect before buying</h2><p className="mt-3">Check the expiry date and reject swollen, leaking, badly dented or damaged packages. Choose fresh produce without extensive bruising or rot. WHO’s safer-food manual specifically advises consumers not to use food beyond its expiry date and to avoid damaged cans.</p></section>
    <section><h2 className="text-2xl font-bold text-slate-950">2. Separate raw and ready-to-eat food</h2><p className="mt-3">Keep raw meat, poultry and seafood away from cooked or ready-to-eat items in the basket, transport bag and refrigerator. Use separate utensils and containers during preparation to reduce cross-contamination.</p></section>
    <section><h2 className="text-2xl font-bold text-slate-950">3. Control time and temperature</h2><p className="mt-3">WHO advises refrigerating cooked and perishable food promptly, preferably below 5°C, keeping cooked food above 60°C before serving, and avoiding more than two hours at room temperature. Put chilled and frozen items away first when you reach home. <a className="font-semibold text-emerald-700 underline" href="https://www.who.int/docs/default-source/wpro---documents/posters/food-safety/the-five-keys-to-safer-food-brochure.pdf" target="_blank" rel="noreferrer">WHO Five Keys brochure</a></p></section>
    <section><h2 className="text-2xl font-bold text-slate-950">4. Cook and reheat thoroughly</h2><p className="mt-3">Cook meat, poultry, eggs and seafood thoroughly and reheat cooked food fully. WHO’s guidance uses 70°C as a practical target for foods such as soups and stews and recommends a food thermometer where possible.</p></section>
    <section><h2 className="text-2xl font-bold text-slate-950">5. Use safe water and raw materials</h2><p className="mt-3">Wash fruit and vegetables with safe water, especially when they will be eaten raw. Choose pasteurized milk where available and do not use products after their expiry date. The WHO’s complete framework is summarized on its <a className="font-semibold text-emerald-700 underline" href="https://www.who.int/activities/promoting-safe-food-handling/five-key-to-safer-food/" target="_blank" rel="noreferrer">Five Keys to Safer Food page</a>.</p></section>
    <aside className="rounded-xl border border-amber-200 bg-amber-50 p-6"><h2 className="text-xl font-bold text-amber-950">Important</h2><p className="mt-2 text-amber-900">This guide provides general food-handling information, not medical advice. Follow package instructions and local public-health notices. If food appears unsafe, do not taste it to test it.</p></aside>
  </div><footer className="mt-12 border-t border-slate-200 pt-7"><p className="font-semibold">Sources</p><ul className="mt-3 list-disc space-y-2 pl-5"><li><a className="text-emerald-700 underline" href="https://www.who.int/news-room/fact-sheets/detail/food-safety">World Health Organization: Food safety fact sheet</a></li><li><a className="text-emerald-700 underline" href="https://www.who.int/activities/promoting-safe-food-handling/five-key-to-safer-food/">World Health Organization: Five keys to safer food</a></li></ul><p className="mt-6"><Link className="font-semibold text-emerald-700" href="/shop">Browse the NOVA MART catalog →</Link></p></footer></article>;
}
