'use client';
import { FormEvent, useState } from 'react';
import { useRouter } from 'next/navigation';
import { useShop } from '@/components/CommerceClient';
import { MARKET } from '@/lib/market';
import { resilientFetch } from '@/lib/resilientFetch';

export default function CheckoutPage() {
  const { items, selectedStore } = useShop(); const router = useRouter(); const [error, setError] = useState(''); const [busy, setBusy] = useState(false);
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!selectedStore) { setError('Choose a store before checkout.'); return; } const form = new FormData(event.currentTarget); const csrf = document.cookie.match(/(?:^|; )customer_csrf=([^;]+)/)?.[1] || ''; setBusy(true); setError(''); try { const cartResponse = await resilientFetch('/api/shopping-cart', { method: 'POST', headers: { 'Content-Type': 'application/json', 'x-csrf-token': csrf }, body: JSON.stringify({ store_id: selectedStore.id }) }); const cart = await cartResponse.json(); if (!cartResponse.ok) throw new Error(cart.error || 'Could not create cart'); for (const item of items) { const itemResponse = await resilientFetch(`/api/shopping-cart/${cart.id}/items`, { method: 'POST', headers: { 'Content-Type': 'application/json', 'x-csrf-token': csrf }, body: JSON.stringify({ product_id: item.product.id, quantity: item.qty }) }); const itemResult = await itemResponse.json(); if (!itemResponse.ok) throw new Error(itemResult.error || 'Could not add every cart item'); } const response = await resilientFetch('/api/checkout/cod', { method: 'POST', headers: { 'Content-Type': 'application/json', 'x-csrf-token': csrf }, body: JSON.stringify({ cart_id: cart.id, store_id: selectedStore.id, idempotency_key: crypto.randomUUID(), delivery_type: form.get('delivery_type'), shipping_name: form.get('name'), shipping_phone: form.get('phone'), shipping_address: form.get('address'), shipping_city: form.get('city'), shipping_state: form.get('state'), shipping_postal_code: form.get('postal_code'), shipping_country: MARKET.countryCode }) }); const result = await response.json(); if (!response.ok) throw new Error(result.error || 'Checkout failed'); router.push(`/account/orders/${result.id}`); } catch (err) { setError(err instanceof Error ? err.message : 'Checkout failed'); } finally { setBusy(false); } }
  if (!items.length) return <div className="shell page"><h1>Your cart is empty</h1></div>;
  return <div className="shell page"><h1>Checkout</h1><p className="mt-2 text-slate-600">Cash on delivery · {selectedStore?.name || 'Choose a store'}</p><form onSubmit={submit} className="mt-8 grid max-w-2xl gap-4 rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><label>Full name<input required name="name" className="mt-1 w-full rounded border p-2" /></label><label>Phone<input required name="phone" placeholder="+977 98XXXXXXXX" className="mt-1 w-full rounded border p-2" /></label><label>Address<input required name="address" className="mt-1 w-full rounded border p-2" /></label><div className="grid gap-4 md:grid-cols-3"><label>City<input required name="city" className="mt-1 w-full rounded border p-2" /></label><label>Province<input required name="state" className="mt-1 w-full rounded border p-2" /></label><label>Postal code<input required name="postal_code" className="mt-1 w-full rounded border p-2" /></label></div><label>Fulfilment<select name="delivery_type" className="mt-1 w-full rounded border p-2"><option value="DELIVERY">Delivery</option><option value="PICKUP">Store pickup</option></select></label>{error && <p role="alert" className="rounded bg-red-50 p-3 text-red-700">{error}</p>}<button disabled={busy} className="primary-btn">{busy ? 'Placing order…' : 'Place COD order'}</button></form></div>;
}
