import type { Metadata } from 'next';
import Link from 'next/link';
import { buildMetadata } from '@/lib/seo';

export const metadata: Metadata = buildMetadata({ title: 'Editorial policy', description: 'How NOVA MART researches, reviews, sources and corrects practical shopping guidance.', path: '/editorial-policy' });

export default function EditorialPolicyPage() {
  return <article className="shell page max-w-4xl"><nav className="breadcrumbs" aria-label="Breadcrumb"><Link href="/">Home</Link><span>›</span><span aria-current="page">Editorial policy</span></nav><header><p className="eyebrow">TRUST AND TRANSPARENCY</p><h1 className="text-4xl font-bold">Editorial policy</h1><p className="mt-4 text-xl leading-8 text-slate-700">NOVA MART publishes practical guidance to help customers make informed shopping and handling decisions. Advice must be useful, traceable and clearly separated from promotions.</p></header><div className="mt-10 space-y-8 text-base leading-7 text-slate-700"><section><h2 className="text-2xl font-bold text-slate-950">Who reviews our guides</h2><p className="mt-2">The NOVA MART Retail Operations Team reviews claims about products, storage and store processes. Medical, legal or regulatory claims require an appropriate primary authority and are not presented as personalized professional advice.</p></section><section><h2 className="text-2xl font-bold text-slate-950">How we use sources</h2><p className="mt-2">We prefer government agencies, public-health bodies, standards organizations and original research. Sources appear beside the claim they support and again in the guide’s source list. We do not invent quotations, credentials, reviews or statistics.</p></section><section><h2 className="text-2xl font-bold text-slate-950">Updates and corrections</h2><p className="mt-2">Every guide displays its publication or review date. Material corrections update the review date. Readers can report an issue through the <Link className="text-emerald-700 underline" href="/contact">contact page</Link>.</p></section><section><h2 className="text-2xl font-bold text-slate-950">Commercial content</h2><p className="mt-2">Prices, availability and promotions may change by store. Editorial guidance does not guarantee availability and does not replace the terms displayed for a specific offer or order.</p></section></div></article>;
}
